apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-quarkus-170255179
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-quarkus-170255179
    app.kubernetes.io/part-of: test-app-170255179
  name: java-quarkus-170255179
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: java-quarkus-170255179
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: java-quarkus-170255179
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/user1-tenant/test-app-170255179/java-quarkus-170255179@sha256:e2214bb3ca4d6aac405ac0d418599c8db4334b3378e34c92929455d0329db5ce
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
